project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!materials/workshop/"

website:
  title: "Influenza"
  twitter-card:
    card-style: summary_large_image
    description: "Years of Work to get Influenza Trend"
    image: "https://raw.githubusercontent.com/rstudio-conf-2022/get-started-quarto/main/preview.jpeg"
  page-footer:
    center: "This page was built with ❤️ and [Quarto](https://quarto.org/) by [Johan Ibrahim](https://github.com/DrJohan)."
  navbar:
    logo: img/logo.png
    logo-href: "https://aesculape.com"
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - text: Slides
        menu: 
          - href: materials/
            text: "First Meeting"
          - href: materials/
            text: "Second Meeting"
  
    right: 
      - icon: github
        href: https://github.com/DrJohan/admcinfluenza.git
      - icon: twitter
        href: https://twitter.com/DrJohan81
  sidebar: 
    style: docked
    contents: 
      - section: "Meeting Slides"
        contents: 
          - href: materials/
          - text: "First Meeting"
          - href: materials/
            text: "Second Meeting"

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

