project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!materials/workshop/"

website:
  title: "Influenza Cases in ADMC"
  twitter-card:
    card-style: summary_large_image
    description: "Two hour workshop on getting started with Quarto"
    image: "https://raw.githubusercontent.com/rstudio-conf-2022/get-started-quarto/main/preview.jpeg"
  page-footer:
    left: "This page was built with ❤️ and [Quarto](https://quarto.org/) by [Tom Mock](https://themockup.blog)."
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - text: Slides
        menu: 
          - href: materials/
            text: "First Meeting"
          - href: materials/
            text: "Second Meeting"
  
    right: 
      - href: "https://aesculape.com"
        text: "Aesculape CRO Malaysia Sdn Bhd"
      - icon: github
        href: https://github.com/DrJohan/admcinfluenza.git
      - icon: twitter
        href: https://twitter.com/DrJohan81
  sidebar: 
    style: docked
    contents: 
      - section: "Meeting Slides"
        contents: 
          - href: materials/
          - text: "First Meeting"
          - href: materials/
            text: "Second Meeting"

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

